version: "3"
services:
  db:
    image: "postgres:11.6"
    container_name: "prisma-pg"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=hilly-sand-pit
      - POSTGRES_DB=prisma
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  app:
    stdin_open: true
    container_name: app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - db
